import Head from 'next/head'
import Image from 'next/image'
import Login from '../Components/login'
import styles from '../styles/Home.module.css'
import { AuthProvider } from './Contexts/AuthContext'

import firebase from '../Repositories/firebase'
import Teste from './teste'


export default function Home(props) {

  if( !props.props.user_email )
    return <Teste />

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <AuthProvider>
          Cookie:
          <Login />
        </AuthProvider>
      </main>

    </div>
  )
}

Home.getInitialProps = async (ctx) => {

  try {
      const authToken = ctx.req.cookies.authToken
    
      //const credentialUser = await firebase.auth().signInWithCustomToken(authToken)
      const credentialUser = 'teste@teste.com'

      const user = credentialUser.user.email
    
      return {
        props: {
          user_email: user
        }
      }
  } catch (error) {
    return {
      props: {
        user_email: ''
      }
    }
  }
}