import { useAuth } from '../Hook/useAuth'
import { Form, Button } from 'react-bootstrap'


export default function Login(){

    const {setCookie, setUsername, username} = useAuth()

    return (
        <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <script src="https://unpkg.com/react/umd/react.production.min.js" crossorigin></script>
          <script
            src="https://unpkg.com/react-dom/umd/react-dom.production.min.js"
            crossorigin></script>
          <script
            src="https://unpkg.com/react-bootstrap@next/dist/react-bootstrap.min.js"
            crossorigin></script>
  
          <script>var Alert = ReactBootstrap.Alert;</script>
        </Head>
  
        <Nav user={user_email}/>
  
        <main className={styles.main}>
            <Form>
            <Form.Group controlId="formBasicEmail">
                <Form.Label>Email address</Form.Label>
                <Form.Control type="email" placeholder="Enter email" />
                <Form.Text className="text-muted">
                We'll never share your email with anyone else.
                </Form.Text>
            </Form.Group>

            <Form.Group controlId="formBasicPassword">
                <Form.Label>Password</Form.Label>
                <Form.Control type="password" placeholder="Password" />
            </Form.Group>
            <Button variant="primary" type="submit">
                Submit
            </Button>
            </Form>
        </main>
  
      </div>


    );
}
